artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Vamsi-Krishna-NP/Just_datasets/raw/main/legal_documents.zip
  locate_data_file: artifacts/data_ingestion/Legal_texts.zip
  unzip_dir: artifacts/data_ingestion