artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Vamsi-Krishna-NP/Just_datasets/raw/main/legal_summary.zip
  locate_data_file: artifacts/data_ingestion/legal_summary.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.yaml
  ALL_REQUIRED_FILES: ["test-data", "train-data"]